- Cargo.toml
- src/crypto
- src/sketching
osc was picking up the kanidm Cargo.toml without
symlinks, but with them the workspace is broken.
Instead switching to no symlinks and excluding
the kanidm Cargo.toml from the build tar.
> osc breaks with workspace errors using symlinks

- src/common/src/config.rs
- src/config/himmelblau.conf.example
- src/daemon/src/daemon.rs
Without this, the pam account entry rejects all.
> daemon: Implement pam allow groups

- src/common/src/idprovider/himmelblau.rs
It's possible for a MFA DAG request to respond
with a successful auth for a user other than the
originally requested user. This could corrupt our
cache and process pam_allow_groups incorrectly.
BUG: https://github.com/openSUSE/himmelblau/issues/37
> Prohibit authentication with changing IDs

- Cargo.toml
- src/nss/src/lib.rs
This corrects the version number in the cargo.toml.
Checklist
> stable 0.1.x Correct the cargo version

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Otherwise the device will not hold an MFA claim.
Also attempt MFA later if username/password
fails with MFA request.
Fixes #
Checklist
> Always force MFA when enrolling the device

- Cargo.toml
- clippy.toml
- src/common/src/idprovider/himmelblau.rs
- src/proto/Cargo.toml
This causes Himmelblau to enroll the
authenticating user in Windows Hello for Pin
authentication. It uses the msal rust library
to associate the user chosen Pin with a rsa key,
which is then enrolled in Windows Hello.
This eliminates the problem with MFA prompts at
the lock screen (which didn't work). The user now
treats the Pin code as a local password.
Fixes #
Checklist
> Windows Hello PIN implementation

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
The DAG request isn't polling properly, and needs
patches to Kanidm. Disable DAG for now until this
is fixed.
Fixes #
Checklist
> Fix fallback DAG deadlock

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
If MFA fails, first check to see if this is
because the user doesn't require MFA. Then
continue to fallback to DAG if necessary.
Fixes #
Checklist
> Fallback to SFA first if MFA fails Browse files

- Cargo.toml
Fixes Bug #111. "AADSTS1400001: Request nonce is
not provided." error when authenticating with
hello key.
Fixes #
Checklist
> Fix Hello PIN Authentication error, no nonce

- Cargo.toml
This requires updating Kanidm also, to match
the new dependency version.
Fixes #
Checklist
> Update the base64urlsafedata version

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Fixes #113. "AADSTS50155: Device authentication failed" when authenticating too quickly after enrollment
Checklist
> Fix Bug #113

- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
This makes sense in public facing situations,
such as when the host has a public facing IP.
Otherwise a Hello PIN could be brute forced.
Fixes #
Checklist
> Add an option for disabling Windows Hello

- src/common/src/idprovider/himmelblau.rs
It's possible Hello PIN auth could be disabled
after a user has completed Hello PIN enrollment.
This ensures authentication with that enrolled
PIN will be disallowed.
Checklist
> Allow disabling Hello PIN auth for enrolled users

- src/common/src/idprovider/himmelblau.rs
The messages incorrectly indicate that we're
skipping MFA. What I meant was we're skipping
Hello enrollment.
Checklist
> Correct the debug messages for Hello skip

- src/common/src/idprovider/himmelblau.rs
This was caused by the provider failing to
refresh the user token, and getting a 'NotFound'
response. Only ever return 'BadRequest' for this
request.
Fixes #
Checklist
> Fix user dropping from NSS

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Fake the user token, but only if it's a valid user which we don't have the object id of yet. Also fix nss requests so the token doesn't get dropped.
Checklist
> Fake user token and fix NSS

- src/common/src/idprovider/himmelblau.rs
The ONLY time we should delete a user from the
cache is if we have a confirmed response from
Azure that the user does not exist. Otherwise it
should remain cached.
Fixes #
Checklist
> Only remove cached user if it doesn't exist

- src/common/src/idprovider/himmelblau.rs
This prevents potential clashing of users in the
cache.
Fixes #
Checklist
> When faking a uuid for NSS, use a random uuid

- src/idmap/src/lib.rs
Otherwise 'Administrator@contoso.samba.org' will get a different uid than 'administrator@contoso.samba.org'.
Checklist
> Always normalize idmap upn inputs

- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
Just because an SFA fallback is permitted by
Azure, doesn't mean we should attempt it by
default. This disables SFA unless explicitly
enabled via configuration.
Fixes #
Checklist
> Disable the SFA fallback by default

- README.md
As of 14-06-2024 this set of packages provides the requirements to build himmelblau on a fresh (gnome) install of tumbleweed
Fixes #
Checklist
> Update required packages for tumbleweed

- Cargo.toml
- platform/opensuse/himmelblaud-tasks.service
- platform/opensuse/himmelblaud.service
- src/nss/Cargo.toml
- src/nss/src/lib.rs
> himmelblaud stops working after suspend

- src/idmap/build.rs
> Compilation fails on Ubuntu, missing ldb header

- src/common/src/resolver.rs
- src/config/himmelblau.conf.example
This flips the default behavior to permit all
users in the configured domains, rather than
to default to prohibit all users. I believe the
prohibit all default is excessive (and comes from
a Kanidm default).
Fixes #
Checklist
> Authorize all users when pam_allow_groups is empty

- .github/workflows/build.yml
- .github/workflows/build_debian_source_package.yml
- .github/workflows/clippy.yml
- .github/workflows/test.yml
- Cargo.toml
- platform/debian/com.microsoft.identity.broker.service
- platform/debian/himmelblaud.service
- platform/debian/org.samba.himmelblau.conf
- platform/opensuse/com.microsoft.identity.broker.service
- platform/opensuse/himmelblaud.service
- platform/opensuse/org.samba.himmelblau.conf
- src/broker/Cargo.toml
- src/broker/src/main.rs
- src/common/src/db.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/daemon/Cargo.toml
- src/daemon/src/broker.rs
- src/daemon/src/daemon.rs
This service implements
com.microsoft.identity.broker1 for mimicking the
behavior of Microsoft's proprietary services.
Fixes #48
Checklist
> Add the D-Bus broker service

- src/pam/src/pam/mod.rs
Rather than leave this on for everyone, implement
it as a pam option that can be turned on if this
issue is encountered.
Fixes #162
Checklist
> Add a pam option for the OpenSSH 2876 workaround

- src/common/src/config.rs
- src/config/himmelblau.conf.example
- src/daemon/src/daemon.rs
This allows debug to be enabled in the
configuration file.
Fixes #152
Checklist
> Add a debug option to the config

- .github/workflows/build_debian_source_package.yml
- .github/workflows/tag-version.yml
- .github/workflows/version-check.yml
- Cargo.toml
This github action is to ensure that the version
number is always incremented in the Cargo.toml
when submitting an MR. Without it, the Debian
build will fail.
Fixes #
Checklist
> Add a version check script

- Makefile
- README.md
Installation instructions need improvements, and we need a `make install` command.
Fixes #186
Checklist
> Improve the user experience for users installing Himmelblau

- Makefile
- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- src/daemon/Cargo.toml
- src/nss/Cargo.toml
- src/pam/Cargo.toml
This is a simple solution to the Ubuntu packaging
needs. `make deb` now generates Ubuntu 22.04 and
24.04 packages.
Fixes #
Checklist
> Add cargo deb build

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
This reverts commit 2fb9f6a11dc123678515cd3b5558bc645ae39fdc. This method may speed up nss, but it also breaks
group memberships.
Fixes #
Checklist
> Revert "Speed up nss requests w/out auth attempt"

- src/pam/src/pam/mod.rs
This could be an invalid response.
Fixes #
Checklist
> Never return the Pam result from get_user()

- Cargo.toml
- src/pam/src/pam/module.rs
See related:
https://github.com/kanidm/kanidm/pull/2960
It seems that a pam or sudo update triggered
this behaviour, which appears to be an external
bug that we need to defend against.
Checklist
> Bug in pam which needs defended against

- platform/debian/himmelblau_sshd.conf
- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
- src/pam/Cargo.toml
> Configuration patches for himmelblau on Debian

- Cargo.toml
- src/cli/src/main.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/pam/Cargo.toml
- src/pam/src/pam/mod.rs
Fixes #219
This is meant to address the issues in #219. Unfortunately, it appears that SSHD is not terminating the auth attempt when the ssh session times out. There isn't really anything we can do about that. We can however, handle this a little better in the communication between the daemon and the pam module. Now the daemon will do nothing unless prompted by the pam module (when polling). I also added code to honor the DAG timeout specified by Microsoft at init time.
Checklist
> Rework the poll logic

- Cargo.toml
- src/cli/src/main.rs
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
- src/glue/src/unix_config.rs
- src/pam/src/pam/mod.rs
> Hello PIN length and offline fixes

- platform/debian/pam-config
This allows us to provide a PIN prompt prior to
pam-unix taking over and sending a password
prompt. pam-unix still works as expected, because
pam-himmelblau skips local users.
Fixes #
Checklist
> PAM should be placed first in the stack

- Cargo.toml
- platform/debian/scripts/postinst
> postinst should not fail on patch or apparmor update

- src/daemon/src/broker.rs
- src/idmap/src/lib.rs
- src/pam/src/pam/mod.rs
This will require a PRTv3. Meanwhile ignore the
scopes request, otherwise the request will fail.
Fixes #
Checklist
> Ignore broker scopes requests for now

- Makefile
- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
- images/rpm/Dockerfile.sle15sp6
- man/man5/himmelblau.conf.5
- man/man8/himmelblaud.8
- man/man8/himmelblaud_tasks.8
- src/daemon/Cargo.toml
> Packaging additions

- platform/debian/pam-config
> Fix Ubuntu PAM fallback to password prompt

- Cargo.toml
- images/rpm/Dockerfile.rocky8
> Enable module for utf8proc-devel in Rocky8

- Cargo.toml
> Fix CVE-2024-11738: rustls network-reachable panic in `Acceptor::accept`

- man/man5/himmelblau.conf.5
- src/common/src/config.rs
- src/common/src/unix_config.rs
Fixes https://github.com/himmelblau-idm/himmelblau/issues/314
Fixes #
Checklist
> Include multi-domain important info in himmelblau.conf man

- src/idmap/src/lib.rs
This is related to #314. With proper error
output, finding the source of a problem will be
easier in the future.
Checklist
> Fix IdmapError to indicate the failure

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Entra Id is now rejecting authentication attempts
to the enrollment service with Single Factor
Authentication. We can work around this by
permitting users to authenticate with SFA if the
host is already enrolled. This means a user with
MFA will be required to enroll the host (which
just requires authenticating once).
Fixes #
> Entra Id no longer permits SFA enrollment

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Entra Id is now rejecting authentication attempts
to the enrollment service with Single Factor
Authentication. We can work around this by
permitting users to authenticate with SFA if the
host is already enrolled. This means a user with
MFA will be required to enroll the host (which
just requires authenticating once).
Fixes #
> Stable 0.8.x Entra Id no longer permits SFA enrollment

- src/daemon/Cargo.toml
Fixes # 346
This was also effecting installation on Debian 12.
> Fix libutf8proc dependency issue on Ubuntu 22.04

- man/man5/himmelblau.conf.5
- platform/debian/himmelblau.conf.example
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
The MS Edge browser app_id grants us the ability
to read group names.
Fixes #270
> Default to request group info via Edge browser

- Cargo.toml
Fixes #411
https://gitlab.com/samba-team/libhimmelblau/-/merge_requests/49
> Support CompanionAppsNotification mfa method

- Cargo.lock
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Sometimes passwordless auth can fail. When this
happens, a browser auth works around the issue by
falling back to a password + MFA auth. We need to
do the same.
> Handle failures in passwordless auth

- Makefile
- flake.nix
I've split the options from the previous version into two sets, `globalOptions` which contains options that can only be set in the `[global]` section, and `domainOptions` that can be set per-domain. These are merged together into the `himmelblau.settings` option which feeds the global section. A new option `himmelblau.domains` is added which takes an attribute set of domain names to configuration options for that domain, and these feed additional sections in the config file named for each domain.
Addititionally, I replaced the ugly string-concat config generation with nixpkgs' `generators.toINI` which means if a new option is added in the future, you won't have to touch the config generation code.
All previously working configurations should continue to work as before.
Additionally I made …
> Add module options for setting per-domain properties.

- Cargo.lock
- Cargo.toml
We can't facilitate setting this up for the user,
so just ignore the prompt. The user can handle
this themselves later.
Fixes #462
> Ignore demands for setting up MS Authenticator

- src/common/src/idprovider/himmelblau.rs
The PRT cookie can be generated w/out network
access, so the request shouldn't be rejected in
offline mode.
> Supplying a PRT cookie to SSO doesn't require network

- src/common/src/idprovider/himmelblau.rs
When a network down is detected, make sure the
URL printed to the log is only ever the base URL.
> Ensure only the base URL is printed to log

- flake.nix
Follow-up from #479
The previous design excluded files we know won't affect the build, preventing rebuilds when updating readme/makefile.
This design includes only files which will affect the build (cargo + src + man + test script).
The trade-off is that adding extra files/folders at the top-level needs to be added to the union if they are needed for package build.
> NixOS: Replace source filter in package derivation

- platform/debian/himmelblaud-tasks.service
- platform/debian/himmelblaud.service
- platform/opensuse/himmelblaud-tasks.service
- platform/opensuse/himmelblaud.service
Ensure that the himmelblau resolver has started before the nss-user target. This target is very early in startup, and ensures that users can be resolved for *any* graphical display manager or incoming ssh request.
> Order services before gdb/nss-user-target

- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
Someone reported an obscure error caused by a
simple typo of writing `domain` in their
himmelblau.conf instead of `domains`. Catch that
particular typo and continue startup, but also
report a better error when there are no domains
configured.
> himmelblau.conf alias `domain` as `domains`

- Cargo.lock
- Cargo.toml
- README.md
- man/man5/himmelblau.conf.5
- platform/debian/himmelblaud-tasks.service
- platform/opensuse/himmelblaud-tasks.service
- src/broker-client/Cargo.toml
- src/broker-client/src/lib.rs
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/unix_proto.rs
- src/config/himmelblau.conf.example
- src/daemon/Cargo.toml
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
- src/pam/src/pam/mod.rs
- src/policies/Cargo.toml
- src/policies/src/chromium_ext.rs
- src/policies/src/compliance_ext.rs
- src/policies/src/cse.rs
- src/policies/src/lib.rs
- src/policies/src/policies.rs
- src/policies/src/scripts_ext.rs
- src/sso/Cargo.toml
- src/sso/src/main.rs
Fixes #60 
Himmelblau now fetches and applies Linux Intune policies when they are configured in Microsoft's Intune portal. This update introduces two new policy implementations for Linux devices:
- **Script Policy:** Scripts from Intune are decoded, written to disk, and scheduled to run via cron.
- **Linux Compliance Policy:** Validates system configuration against policy settings such as allowed Linux distributions, required device encryption, and password policy minimum length (which applies to the Hello PIN length).
**Important Notes:**
- Himmelblau now fully supports marking devices as compliant with Intune MDM policies.
- When Intune policy application is enabled, devices which fail to comply with Intune policy will be prohibited from authenticating users.
**Current Limitations:**
- …
> Linux Intune policy application

- platform/debian/himmelblaud-tasks.service
In my test Debian Bookworm VM image the following occurs:
```
systemd[1]: Starting himmelblaud-tasks.service - Himmelblau Local Tasks...
(ud_tasks)[499]: himmelblaud-tasks.service: Failed to set up mount namespacing: /run/systemd/unit-root/run/himmelblaud: No such file or d>
(ud_tasks)[499]: himmelblaud-tasks.service: Failed at step NAMESPACE spawning /usr/sbin/himmelblaud_tasks: No such file or directory
systemd[1]: himmelblaud-tasks.service: Main process exited, code=exited, status=226/NAMESPACE
systemd[1]: himmelblaud-tasks.service: Failed with result 'exit-code'.
systemd[1]: Failed to start himmelblaud-tasks.service - Himmelblau Local Tasks.
```
For completeness, after starting himmelblaud-tasks manually, the basic 2FA login works to a tenant (not yet far enough to say anything about …
> Enforce strict order for the systemd units

- Cargo.lock
- Cargo.toml
Bumps the cargo group with 1 update: [tracing-subscriber](https://github.com/tokio-rs/tracing).
Updates `tracing-subscriber` from 0.3.19 to 0.3.20
- [Release notes](https://github.com/tokio-rs/tracing/releases)
- [Commits](https://github.com/tokio-rs/tracing/compare/tracing-subscriber-0.3.19...tracing-subscriber-0.3.20)
---
updated-dependencies:
- dependency-name: tracing-subscriber dependency-version: 0.3.20 dependency-type: direct:production dependency-group: cargo ...
Fixes #
> deps(rust): bump tracing-subscriber in the cargo group

- platform/el/authselect/README
- platform/el/authselect/fingerprint-auth
- platform/el/authselect/nsswitch.conf
- platform/el/authselect/password-auth
- platform/el/authselect/postlogin
- platform/el/authselect/smartcard-auth
- platform/el/authselect/system-auth
- src/daemon/Cargo.toml
- src/o365/Cargo.toml
- src/pam/Cargo.toml
This should resolve various pam configuration issues on the RHEL/Rocky/Fedora distros. Also is available on openSUSE, but isn't default.
> Add authselect module for Rocky/Fedora

- .github/workflows/ci.yml
- deny.toml
This checks that Himmelblau is compliant with all
dependency licenses.
Fixes #
> Add CI check for licenses
