himmelblau-idm/himmelblau

- TODO.md
- src/himmelblaud/Cargo.toml
- src/himmelblaud/src/daemon.rs
- src/msal/src/misc.rs
- src/unix_common/Cargo.toml
- src/unix_common/src/config.rs
- src/unix_common/src/constants.rs
- src/unix_common/src/lib.rs
- src/unix_common/src/memcache.rs
Improve the memcache, and send a lookup to the odc for group membership information.
> memcache: Create a memcache for user and group caching

- Cargo.toml
- TODO.md
- src/himmelblaud/src/daemon.rs
- src/unix_common/Cargo.toml
- src/unix_common/src/cache.rs
- src/unix_common/src/constants.rs
- src/unix_common/src/lib.rs
Pickle the cache to a file on disk.
> cache: Make the cache persistent

- src/aad-tool/Cargo.toml
- src/aad-tool/src/main.rs
- src/himmelblaud/src/daemon.rs
- src/msal/Cargo.toml
- src/msal/src/misc.rs
- src/unix_common/src/config.rs
- src/unix_common/src/unix_proto.rs
This is not perfect, but is an improvement. Now authentication will happen as a regular user, and the actual enrollment happens within the daemon.
> Enrollment process fixes

- Cargo.toml
- src/himmelblaud/Cargo.toml
- src/himmelblaud/src/daemon.rs
- src/policies/Cargo.toml
- src/policies/src/chromium_ext.rs
- src/policies/src/cse.rs
- src/policies/src/lib.rs
- src/policies/src/policies.rs
This leaves a lot to be desired, but is the very introduction with more to follow. Technically this is incorrect, since it is applying user policy to the whole host. These chrome policies need to be applied directly to the user's chrome/chromium profile (if possible, I haven't found documentation on how to do this).
> Basic Group Policy implementation

- src/msal/src/authentication.rs
We can use this flow to prompt for creds on a
different device (such as a cell phone) when
we're unable to perform MFA at the login window.
> msal: Add bindings for device auth flow

- src/aad-tool/src/main.rs
- src/himmelblaud/config/himmelblau.conf.example
This is far from functional. Turn it off by
default for now.
> aad-tool: Disable enrollment by default

- src/common/src/idprovider/himmelblau.rs
> Always match DAG where present

- .gitmodules
> Switch to kanidm master

- Cargo.toml
- README.md
- TODO.md
- platform/opensuse/himmelblaud-tasks.service
- platform/opensuse/himmelblaud.service
- src/common/Cargo.toml
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/file_permissions.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/lib.rs
- src/common/src/unix_passwd.rs
- src/config/himmelblau.conf.example
- src/daemon/Cargo.toml
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
- tests/test.sh
This mostly works, but the daemon hangs when trying to create the PublicClientApplication (or maybe it hangs in the auth attempt, I'm not sure). The pam module times out waiting for the daemon to respond, but the daemon does eventually respond with a successful authentication.
> daemon: Run himmelblaud as non-root dynamic user

- Cargo.toml
> Update version to 0.1.0

- TODO.md
> Remove MFA from TODO

- tests/test.sh
> tests: Fix tasks daemon name typo

- src/config/himmelblau.conf.example
Fixes config issues.
Checklist
> Stable 0.1.0 doc fix

- Cargo.toml
- src/cli/Cargo.toml
- src/cli/src/main.rs
- src/common/src/config.rs
> cli: Improve aad-tool options and interface

- src/cli/src/opt/tool.rs
> cli: Add missing cli opt file

- src/cli/src/main.rs
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
- src/glue/src/unix_config.rs
- src/msal/src/authentication.rs
> Random bits changed during enrollment work that can merge now

- Cargo.toml
- src/nss/src/lib.rs
Updates the main branch version to 0.1.2.
Checklist
> Update version to 0.1.2

- clippy.toml
- src/common/src/client.rs
- src/common/src/client_sync.rs
- src/common/src/config.rs
- src/common/src/db.rs
- src/common/src/file_permissions.rs
- src/common/src/file_permissions/mod.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/idprovider/mod.rs
- src/common/src/lib.rs
- src/common/src/resolver.rs
- src/common/src/unix_passwd.rs
- src/common/src/unix_proto.rs
- src/daemon/src/daemon.rs
- src/nss/Cargo.toml
- src/proto/src/lib.rs
- src/proto/src/v1.rs
> Stable 0.1.x backports

- Cargo.toml
- TODO.md
> Version 0.2.0

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> Update to latest msal

- Cargo.toml
> Update msal crate again

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
> stable 0.2.x updates

- .gitmodules
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/proto/src/internal
- src/proto/src/lib.rs
- src/proto/src/v1
> Enhanced MFA

- .gitignore
> Update the gitignore

- .github/dependabot.yml
- .gitmodules
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/daemon/src/daemon.rs
Depends on https://github.com/kanidm/kanidm/pull/2672
Checklist
> WIP: Use the Kanidm MFA patches

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/dependabot_auto_merge.yml
- scripts/dependabot_automerge_check.sh
- src/common/Cargo.toml
> Add build and dependabot_automerge workflows 

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/dependabot_auto_merge.yml
- Cargo.toml
- scripts/dependabot_automerge_check.sh
- src/common/Cargo.toml
> Add build and dependabot_automerge workflows

- .github/workflows/build.yml
- .github/workflows/clippy.yml
- .github/workflows/dependabot_auto_merge.yml
Also remove duplicate actions
Fixes #
Checklist
> Enable actions on stable branches

- src/common/Cargo.toml
- src/common/src/idmap.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/lib.rs
> Add rid idmapping (replacing existing idmap)

- .github/workflows/build.yml
- .github/workflows/clippy.yml
- .github/workflows/dependabot_auto_merge.yml
> Add github workflows for the 0.3.x branch

- .github/workflows/build.yml
- .github/workflows/clippy.yml
- .github/workflows/dependabot_auto_merge.yml
- Cargo.toml
> Update version main

- README.md
> Update README.md with Matrix contact info

- Cargo.toml
> Stable 0.3.x bug111

- Cargo.toml
- TODO.md
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
> stable 0.3.x updates

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> Fixes for 0.3.x stable branch

- src/cli/src/main.rs
> Fix aad-tool to handle MFA

- src/cli/src/main.rs
> Fix aad-tool to handle MFA in 0.3.x stable branch

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Resolves most of the SSH issues caused by NSS failures.
Checklist
> Stable 0.3.x fixes

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
- src/graph/src/user.rs
> Fix group lookup failure

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> Fix a refresh token leak in debug from msal (stable-0.4.x)

- Cargo.toml
- LICENSE
> Relicensing as GPL3, as SSSD source inclusion requires

- src/common/src/idprovider/himmelblau.rs
> OneWaySMS is additionally a valid OTP

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> MS Authenticator with PhoneAppNotification fixes

- Cargo.toml
- LICENSE
- src/common/src/idprovider/himmelblau.rs
> Backports to 0.4.x stable

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> Fix ConsolidatedTelephony MFA method

- platform/opensuse/himmelblaud-tasks.service
- platform/opensuse/himmelblaud.service
Fixes # https://github.com/himmelblau-idm/himmelblau/issues/155
Checklist
> himmelblaud stops working after suspend

- Cargo.toml
- src/common/Cargo.toml
- src/nss/Cargo.toml
- src/nss/src/lib.rs
> Switch to using libhimmelblau

- Cargo.toml
This is prior to the libhimmelblau move.
Fixes #
Checklist
> Specifically use msal 0.2.6

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/nss/src/lib.rs
> Update to libhimmelblau version 0.2.9

- .gitmodules
- src/common/Cargo.toml
- src/daemon/src/tasks_daemon.rs
> Fix CI failures caused by cargo 1.80.1

- .github/workflows/build_debian_source_package.yml
- .github/workflows/build_debian_source_package_strict.yml
> Debian package fixes

- .github/workflows/build_debian_source_package.yml
- .github/workflows/build_debian_source_package_strict.yml
> Fix debian package version

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
Includes automatic fallback to DAG when MFA
fails, and various reliability improvements.
Fixes #178
Checklist
> Update to the latest libhimmelblau

- .github/workflows/build_debian_source_package.yml
- .github/workflows/tag-version.yml
- .github/workflows/version-check.yml
> Fix Debian packaging in main

- Cargo.toml
- Makefile
- README.md
> Stable 0.5.x make install

- debian/rules
> Attempt to fix the cargo version in launchpad build

- .github/workflows/build_debian_source_package.yml
- Cargo.toml
> Add libdbus-1-dev dep

- .github/workflows/build_debian_source_package.yml
> libdbus-1-dev deb build dep

- Makefile
> Makefile typo fixes

- Cargo.toml
- platform/opensuse/himmelblaud.service
- src/broker/Cargo.toml
- src/broker/src/main.rs
- src/common/src/config.rs
- src/common/src/constants.rs
- src/config/himmelblau.conf.example
- src/daemon/Cargo.toml
- src/daemon/src/broker.rs
- src/daemon/src/daemon.rs
This resolves the himmelblaud hang caused by
async/block_on issues. The broker now
communicates with himmelblaud via a unix socket,
instead of an additional dbus service.
Fixes #
Checklist
> Fixes for the dbus broker

- src/pam/Cargo.toml
> Correct installation directory of the deb pam module

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/daemon/src/broker.rs
> Speed up nss requests w/out auth attempt

- Makefile
- platform/debian/apparmor.unix-chkpwd.local
- platform/debian/com.microsoft.identity.broker1.service
- platform/debian/pam-config
- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
- src/pam/Cargo.toml
- src/pam/src/pam/module.rs
> PAM fixes (mostly for ubuntu)

- Cargo.toml
- Makefile
- platform/debian/apparmor.unix-chkpwd.local
- platform/debian/himmelblau_sshd.conf
- platform/debian/pam-config
- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
- src/pam/Cargo.toml
> Stable 0.6.x Debian packaging fixes

- platform/debian/himmelblau_sshd.conf
- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
- src/pam/Cargo.toml
Also only configure sshd if the package
is installed.
Fixes #227
Checklist
> Add a sshd soft depends for the deb package

- Cargo.toml
- platform/debian/scripts/postinst
- src/glue/src/unix_config.rs
> Ensure local users are ignored when CN mapping

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
> Stable 0.6.x fail on bad password

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
> Fail on bad password

- Cargo.toml
- src/cli/src/main.rs
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
- src/glue/src/unix_config.rs
- src/pam/src/pam/mod.rs
> Hello PIN length and offline fixes

- Cargo.toml
- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
- platform/debian/sshd_config
- src/pam/Cargo.toml
- src/sshd-config/Cargo.toml
> Move sshd config into it's own debian package

- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- src/common/src/idprovider/himmelblau.rs
- src/daemon/Cargo.toml
> Fixes for the main branch

- Cargo.toml
- platform/debian/pam-config
- src/common/src/idprovider/himmelblau.rs
> Stable 0.6.x backports

- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
> Don't use sudo in postinst/postrm scripts for deb

- platform/debian/scripts/postinst
> postinst should not fail on patch or apparmor update

- Cargo.toml
- platform/debian/himmelblau.conf.example
- platform/debian/scripts/postinst
- platform/debian/scripts/postrm
- src/daemon/Cargo.toml
Fixes #228
Fixes #224
Checklist
> Resolve some Ubuntu issues backport to stable 0.6.x

- Makefile
- images/rpm/Dockerfile.rocky9
- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- src/daemon/Cargo.toml
- src/nss/Cargo.toml
- src/pam/Cargo.toml
- src/sshd-config/Cargo.toml
> Add RPM packaging for EL9

- .gitignore
- Makefile
- images/rpm/Dockerfile.rocky8
- platform/el/sshd_config
- src/sshd-config/Cargo.toml
Fixes #143
Fixes #206 
Checklist
> RPM Packaging for Rocky 8

- platform/debian/himmelblau.conf.example
- src/common/src/config.rs
- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/config/himmelblau.conf.example
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
> Adding compliance options

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/daemon/src/broker.rs
> Specify scopes when making an SSO request

- images/rpm/Dockerfile.tumbleweed
- platform/debian/himmelblau.conf.example
- src/config/himmelblau.conf.example
> Hello support depends on openssl3

- Cargo.toml
- Makefile
- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
- images/rpm/Dockerfile.rocky8
- images/rpm/Dockerfile.rocky9
- images/rpm/Dockerfile.sle15sp6
- images/rpm/Dockerfile.tumbleweed
- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- src/sso/Cargo.toml
- src/sso/LICENSE.md
- src/sso/src/chrome/extension.json
- src/sso/src/chrome/linux_entra_sso.json
- src/sso/src/chrome/policies.json
- src/sso/src/firefox/linux_entra_sso.json
- src/sso/src/firefox/policies.json
- src/sso/src/linux-entra-sso.py
> Backports to stable

- images/rpm/Dockerfile.rocky8
- images/rpm/Dockerfile.rocky9
> Fix missing dependency utf8proc_NFKC_Casefold

- images/rpm/Dockerfile.rocky8
> Enable module for utf8proc-devel in Rocky8

- Cargo.toml
> Stable 0.7.x update libhimmelblau

- .github/workflows/build.yml
- .github/workflows/clippy.yml
- .github/workflows/test.yml
- Cargo.toml
- README.md
- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
- images/rpm/Dockerfile.rocky9
- images/rpm/Dockerfile.tumbleweed
- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/daemon/Cargo.toml
- src/daemon/src/daemon.rs
- src/glue/src/unix_config.rs
- src/nss/src/implementation.rs
- src/pam/Cargo.toml
- src/pam/src/pam/constants.rs
- src/pam/src/pam/items.rs
- src/pam/src/pam/mod.rs
> Hello Pin changes via `passwd` command

- .github/workflows/build.yml
- .github/workflows/clippy.yml
- .github/workflows/test.yml
- Cargo.toml
- README.md
- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
- images/rpm/Dockerfile.rocky9
- images/rpm/Dockerfile.tumbleweed
- images/ubuntu/Dockerfile.22.04
- images/ubuntu/Dockerfile.24.04
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/daemon/Cargo.toml
- src/daemon/src/daemon.rs
- src/glue/src/unix_config.rs
- src/nss/src/implementation.rs
- src/pam/Cargo.toml
- src/pam/src/pam/constants.rs
- src/pam/src/pam/items.rs
- src/pam/src/pam/mod.rs
Fixes https://github.com/himmelblau-idm/himmelblau/issues/279
Checklist
> Stable 0.7.x Hello Pin changes via `passwd` command

- Cargo.toml
- Makefile
- images/deb/Dockerfile.debian12
- images/deb/Dockerfile.ubuntu22.04
- images/deb/Dockerfile.ubuntu24.04
> Stable 0.7.x Add Debian 12 packaging

- Makefile
- images/deb/Dockerfile.debian12
- images/deb/Dockerfile.ubuntu22.04
- images/deb/Dockerfile.ubuntu24.04
> Add Debian 12 packaging

- Cargo.toml
- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
> Stable 0.7.x fedora build deps

- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
> Fix Fedora build dependencies

- Cargo.toml
- man/man5/himmelblau.conf.5
- platform/debian/himmelblau.conf.example
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
> Fix Multi Domain support not working

- Cargo.toml
- man/man5/himmelblau.conf.5
- platform/debian/himmelblau.conf.example
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
> Stable 0.7.x Fix Multi Domain support not working

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/pam/src/pam/mod.rs
> Implement NGC Passwordless authentication

- src/daemon/src/daemon.rs
> Add a span around server initialisation for correct log coalescing

- Cargo.toml
- man/man5/himmelblau.conf.5
- platform/debian/himmelblau.conf.example
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
> Use posix attributes synchronized from on-prem AD

- Cargo.lock
- Cargo.toml
- man/man5/himmelblau.conf.5
- platform/debian/himmelblau.conf.example
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/lib.rs
- src/common/src/mapping.rs
- src/common/src/resolver.rs
- src/config/himmelblau.conf.example
- src/daemon/src/broker.rs
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
- src/nss/src/implementation.rs
Fixes #372 #371
Also fixes a missed auth code redirect (found during a debugging session).
> Various fixes for 0.9.x

- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
Fixes a missed auth code redirect (found during a debugging session).
> Resolve missed auth code redirect

- .github/workflows/ci.yml
- .github/workflows/nixosbuild.yml
> Move the NixOS CI to a different workflow (w/out main)

- src/common/src/db.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/resolver.rs
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
- src/pam/src/pam/mod.rs
> Dramatically improve debug logging

- src/common/src/db.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/daemon/src/broker.rs
> Resolve migration error `real_gidnumber` missing

- platform/debian/pam-config
> Ubuntu PAM module configuration to change PIN

- platform/debian/himmelblaud-tasks.service
- platform/debian/himmelblaud.service
- platform/opensuse/himmelblaud-tasks.service
- platform/opensuse/himmelblaud.service
> Utilize systemd notify to avoid tasks started fail

- src/common/src/config.rs
- src/daemon/src/tasks_daemon.rs
- src/nss/src/implementation.rs
This way we don't have to deal with the mapping
cache unless it is actually enabled.
Fixes #
> Isolate the name mapping so it only happens if enabled

- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
> Ensure tasks daemon creates files w/ correct gid

- man/man5/himmelblau.conf.5
These recommendations might change, depending on the results of some testing, but for now, these are accurate.
> Document the requirements for app_id

- Cargo.toml
> Version 1.0.0

- Cargo.lock
- man/man5/himmelblau.conf.5
- src/cli/src/main.rs
- src/common/src/resolver.rs
- src/daemon/src/tasks_daemon.rs
This is a collection of patches which will be backported for 0.9.1.
Fixes #402
> Patches for backport to 0.9.1

- Cargo.lock
- Cargo.toml
Fixes #411 
https://gitlab.com/samba-team/libhimmelblau/-/merge_requests/49
> Support CompanionAppsNotification mfa method

- Cargo.lock
- Cargo.toml
- platform/debian/pam-config
- platform/debian/scripts/postinst
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/daemon/src/tasks_daemon.rs
- src/pam/src/pam/mod.rs
- src/sso/src/main.rs
> Improve offline auth handling

- Cargo.lock
- Cargo.toml
- platform/debian/pam-config
- platform/debian/scripts/postinst
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/resolver.rs
- src/daemon/src/tasks_daemon.rs
- src/sso/src/main.rs
Fixes https://github.com/himmelblau-idm/himmelblau/issues/441, https://github.com/himmelblau-idm/himmelblau/issues/438, and https://github.com/himmelblau-idm/himmelblau/issues/437
> Offline check improvements

- src/pam/Cargo.toml
> Ensure the pam module is installed correctly for SLE

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/cli/src/main.rs
- src/common/Cargo.toml
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/idprovider/interface.rs
- src/common/src/lib.rs
- src/common/src/nss_cache.rs
- src/common/src/resolver.rs
- src/common/src/unix_proto.rs
- src/daemon/src/daemon.rs
- src/nss/src/implementation.rs
- src/pam/src/pam/mod.rs
> Various fixes for issues discovered on-site with users

- images/rpm/Dockerfile.rocky9
A dependency for building rocky9 with passwd interactive was removed upstream.
> Fix rocky9 build

- Cargo.lock
- Cargo.toml
- README.tokio-console.md
- src/daemon/Cargo.toml
- src/daemon/src/daemon.rs
I have built and checked this compiles, but I haven't fully tested it (as this doesn't easily run on macos). This should build and enable the tokio console, which allows detection of and alerting of some possible mistakes.
> Add tokio console

- Cargo.lock
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/daemon/src/daemon.rs
- src/daemon/src/tasks_daemon.rs
Sometimes the resolver could deadlock if the network went down during an nss request.
Also fix systemd notify to indicate properly when the daemon is up.
> Fix deadlock in nss when network goes down

- src/sso/src/firefox/policies.json
> Update linux-entra-sso to latest version

- Cargo.lock
- Cargo.toml
- src/cli/Cargo.toml
- src/cli/src/main.rs
- src/cli/src/opt/tool.rs
- src/common/src/auth.rs
- src/common/src/idprovider/himmelblau.rs
- src/common/src/lib.rs
- src/common/src/tpm.rs
- src/daemon/src/daemon.rs
- src/pam/src/pam/mod.rs
This new command `aad-tool enumerate` will cache
the uid and gid from cloud synced rfc2307 attrs.
> aad-tool command for enumerating users and groups

- src/common/src/config.rs
> Never write the app_id to the server config

- src/cli/src/main.rs
- src/common/src/hello_pin_complexity.rs
- src/common/src/lib.rs
- src/pam/src/pam/mod.rs
> PIN complexity to match Windows

- Cargo.lock
- src/cli/src/main.rs
- src/common/Cargo.toml
- src/common/src/auth.rs
- src/common/src/lib.rs
- src/common/src/pam.rs
- src/pam/Cargo.toml
- src/pam/src/pam/constants.rs
- src/pam/src/pam/mod.rs
> aad-tool fails if the user has FIDO2 enabled

- Makefile
- images/deb/Dockerfile.debian12
- images/deb/Dockerfile.ubuntu22.04
- images/deb/Dockerfile.ubuntu24.04
- images/rpm/Dockerfile.fedora41
- images/rpm/Dockerfile.rawhide
- images/rpm/Dockerfile.rocky8
- images/rpm/Dockerfile.rocky9
- images/rpm/Dockerfile.sle15sp6
- images/rpm/Dockerfile.tumbleweed
- man/man5/himmelblau.conf.5
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
- src/config/himmelblau.conf.example
> Make the bad PIN count configurable and make bad attempts wait

- man/man5/himmelblau.conf.5
- src/common/src/auth.rs
- src/common/src/config.rs
- src/config/himmelblau.conf.example
> Allow altering the password and PIN prompt messages

- Cargo.lock
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> Cache encrypted PRT to disk for offline login SSO

- Cargo.lock
- Cargo.toml
> Stable 0.9.x: Fix Intermittent auth issue AADSTSError 16000

- DEVELOPER-BUILDS.md
- README.md
> Add instructions for creating developer builds

- src/common/src/idprovider/himmelblau.rs
> If bad PIN count is exceeded, delete the Hello key

- Cargo.lock
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
> Fix Intermittent auth issue AADSTSError 16000

- Makefile
- images/rpm/Dockerfile.sle16
- src/daemon/Cargo.toml
- src/nss/Cargo.toml
- src/nss/scripts/postinst
> Correct the RPM postinst script syntax

- Cargo.toml
- src/daemon/Cargo.toml
- src/nss/Cargo.toml
- src/nss/scripts/postinst
> Fix Missing /var/cache/himmelblau-policies directory causes himmelblaud-tasks startup failure

- Makefile
> Add help output to the Makefile

- .github/dependabot.yml
Update the dependabot config to target all supported stable branches.
Fixes #
> Update dependabot.yml to target all stable branches

- Cargo.lock
- Cargo.toml
- src/common/src/idprovider/himmelblau.rs
- src/daemon/src/daemon.rs
> Fix mixed case names in Hello PIN lookup, and increase maximum group lookup

- Makefile
> Fix RHEL8 package signing

- .github/workflows/fuzz_pr.yml
- .github/workflows/fuzz_weekly.yml
- Cargo.lock
- Cargo.toml
- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/config.rs
- src/common/src/config.rs
- src/common/src/idprovider/himmelblau.rs
- supply-chain/audits.toml
- supply-chain/imports.lock
Right now it only fuzzes the himmelblau.conf option handlers, but the point is to add the fuzzing framework, and we'll expand on it in follow up commits.
> Add basic fuzzing

- .github/workflows/fuzz_pr.yml
- .github/workflows/fuzz_weekly.yml
- Makefile
- man/man5/himmelblau.conf.5
- scripts/gen_dockerfiles.py
- src/common/src/config.rs
- src/common/src/constants.rs
- src/common/src/idprovider/himmelblau.rs
> Support for Entra registered devices
